apiVersion: ngrok.com/v1alpha1
kind: Ngrok
metadata:
  name: http-simple
  namespace: default
spec:
  # protocol used, currently support http & tcp
  # tcp is less tested, please create issue 
  # default is http
  protocol: http

  # service section represent
  # the service name in the same namespace
  service: nginx-service
  
  # port section represent
  # the service port in the same namespace
  port: 80
